### ISSUE TITLE
Fichier trash1.html

### ISSUE THREAD

**Issue by Florianlouton** [Florianlouton/ProjetIPME#1]
Je ne voie pas l'intérêt du fichier trash1.html

![image](https://user-images.githubusercontent.com/16013915/46939745-6a64cd00-d067-11e8-92db-a53d8eacc1e5.png)

**Comment by Florianlouton** [comment]
![s-l300](https://user-images.githubusercontent.com/16013915/46939944-d810f900-d067-11e8-834e-69c2bdaf5c9a.jpg)

**Comment by Siriondiil** [comment]
**oof**
